name: Node.js CI							#Nome Action

on:											#Events list
  push:										#Trigger su push nel master
    branches: [ master ]
  pull_request:								#Trigger su push nel master
    branches: [ master ]								
    
jobs:										#Lista di Jobs				
  build:									#Nome Job
    runs-on: ubuntu-latest					#Specifica del Runner
    steps:									#Lista di step
      - uses: actions/checkout@v2			#Action: specifica ambiente Node.js
      - uses: actions/setup-node@v2			
        with:
          node-version: '14'
      - run: npm install 					#Installazione dipendenze esterne
      - run: npm test						#Esecuzione script di test	